# Generated by Django 4.0.4 on 2022-05-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=10)),
                ('file1', models.FileField(upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currency_name', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('Date', models.CharField(max_length=100)),
                ('converted_currency', models.CharField(max_length=10)),
                ('converted_amount', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.company')),
            ],
        ),
    ]
